services:
    backend:
        image: huydev2k4/cms-backend:latest
        ports:
            - "8080:5000"
        env_file:
            - ./backend/.env
        depends_on:
            - redis
        restart: unless-stopped

    admin-frontend:
        image: huydev2k4/cms-admin-frontend:latest
        ports:
            - "8081:8080"
        env_file:
            - ./admin-frontend/.env
        restart: unless-stopped

    client-frontend:
        image: huydev2k4/cms-client-frontend:latest
        ports:
            - "8082:8081"
        restart: unless-stopped

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        restart: unless-stopped

volumes:
    redis-data:
